testimonialArr = [
  {
    avatarUrl: "3ako6QX.png",
    userName: "中山猴王",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚...的...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "8O1cOnG.png",
    userName: "新樂街吳小姐",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚ㄉ",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "8WwZsLS.png",
    userName: "鼓波街劉先生",
    purchasedItem: "Antony 雙人床架",
    userComment: "好讚...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "C0NDvSA.png",
    userName: "登山街陳先生",
    purchasedItem: "Antony 雙人床架",
    userComment: "no more pain",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "CUFGfay.png",
    userName: "臨海路黃先生",
    purchasedItem: "Antony 雙人床架",
    userComment: "holy...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "hUsTZDm.png",
    userName: "駁遊路林小姐",
    purchasedItem: "Antony 雙人床架",
    userComment: "like being in paradise",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "I9L7WOr.png",
    userName: "師大路大師",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚...的...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "NycuPVy.png",
    userName: "大港橋居民",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚...的...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "W7fyzp2.png",
    userName: "裕誠路育承",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚...的...",
    itemUrl: "npA3DgP.png",
  },
  {
    avatarUrl: "zdFOQIv.png",
    userName: "西子灣灣家",
    purchasedItem: "Antony 雙人床架",
    userComment: "讚...的...",
    itemUrl: "npA3DgP.png",
  },
];
